<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-05-23T19:10:58+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'fr_FR',
    'version_installed' => '9.3.1',
    'version_db_installed' => '20240515173142',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1716483882,
        'latest_version' => '9.3.1',
    ],
    'email' => [
        'default' => [
            'address' => 'stanig2106@gmail.com',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
];
